CREATE TABLE `samples` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refrigerator_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('normal','warning','critical','used','pending') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `temperature` decimal(5,1) NOT NULL,
  `collected_at` date DEFAULT NULL,
  `patient_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `uploader` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `compartment` enum('upper','lower') COLLATE utf8mb4_unicode_ci NOT NULL,
  `position` int NOT NULL,
  `note` text COLLATE utf8mb4_unicode_ci,
  `volume` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `grid_rows` int NOT NULL DEFAULT '2',
  `grid_cols` int NOT NULL DEFAULT '2',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fridge` (`refrigerator_id`),
  KEY `idx_fridge_comp_pos` (`refrigerator_id`,`compartment`,`position`),
  KEY `idx_samples_active_position` (`refrigerator_id`,`deleted_at`,`compartment`,`position`),
  CONSTRAINT `samples_ibfk_1` FOREIGN KEY (`refrigerator_id`) REFERENCES `refrigerators` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
