CREATE TABLE `upper_items` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `refrigerator_id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `row_number` int NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `item_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '样本',
  `box_mode` enum('simple','precise') COLLATE utf8mb4_unicode_ci DEFAULT 'simple',
  `grid_rows` int DEFAULT NULL,
  `grid_cols` int DEFAULT NULL,
  `quantity` int DEFAULT '1',
  `owner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `note` text COLLATE utf8mb4_unicode_ci,
  `image_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qr_code` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `deleted_by` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `refrigerator_id` (`refrigerator_id`),
  CONSTRAINT `upper_items_ibfk_1` FOREIGN KEY (`refrigerator_id`) REFERENCES `refrigerators` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
